name: Deploy to QA
on:
  push:
    branches:
    - main
jobs: 
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ca-central-1
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm --no-git-tag-version version patch
      - run: npm run build
      - run: aws s3 sync ./dist/trx-ui/ s3://trx.backofficeclouds.com
  